<?php
declare(strict_types=1);

// PLEASE DO NOT EDIT THIS FILE

// CONTACT me at post@bie.no if you have any questions!

?>

<center>
<a href="http://www.bie.no/products/phpodp"><img src="phpodp.gif" border=0 alt="download this script for free!"></a>
</center>